@tool
extends Panel

#region Определяемое при использовании
## Индекс -> Имя устройства. Нужен для предсказуемого
## порядка отображения: верх->вниз или лево->право.
## Имя устройства должно быть взято из settings.gd
@export var index_to_unit_names: Array[StringName]
## Минимальная частота, МГЦ
@export var freq_min: float
## Максимальная частота, МГЦ
@export var freq_max: float
## Цвет диапазона передатчика на шкале
@export var color_tx: Color
## Цвет диапазона приёмника на шкале
@export var color_rx: Color
## Цвет нечётных строк шкалы
@export_color_no_alpha var color_odd: Color
## Цвет чётных строк шкалы
@export_color_no_alpha var color_even: Color
#endregion

#region Загружаемые ресурсы
@export var matrix_conf: Array[Texture]
@export_file('*.tscn') var table_headers: Array[String]
@export_file('*.tscn') var table_cells: Array[String]
@export_file('*.png') var image_file_rx: String
@export_file('*.png') var image_file_tx: String
@export var table_rows_hight: int
@export var table_column_widths: Array[int]
@export var table_header_widths: Array[int]
@export var table_header_text: Array[String]
#endregion

#region Заполняется автоматически при запуске
var name_to_index: Dictionary[StringName, int]  ## Имя устройства -> Индекс
var name_to_scale: Dictionary[StringName, GridContainer]  ## Имя устройства -> Шкала
var table_cell_row: Array
#endregion

#region Заполняется во время работы
var yems_info: Dictionary[StringName, Dictionary]  ## Доклады
var yems_cmd: Dictionary[StringName, Dictionary]   ## Команды
## Порядок следования кластеров в таблице.
## {имя_устройства: { имя_кластера: индекс_в_таблице } }
var cnames_table: Dictionary[StringName, Dictionary]
## Порядок следования кластеров на шкале.
## {имя_устройства: { индекс_на_шкале } }
var pnames_scale: Dictionary[StringName, int]
#endregion


enum CalsterStatus {
    CLASTER_DELETED,
    CLASTER_RUNNING
}


func _ready() -> void:
    # Инициализировать переменные
    for i in index_to_unit_names.size():
        var nm: = index_to_unit_names[i]
        name_to_index[nm] = i
        yems_info[nm] = {}
        cnames_table[nm] = {}
    var btns_scales = get_tree().get_nodes_in_group('кнопки-шкалы')
    for node in btns_scales:
        var nm: = node.get_meta('unit_name') as StringName
        node.connect('pressed', map_yems_data_to_table.bind(nm))
    var claster_scales = get_tree().get_nodes_in_group('шкалы-кластеров')
    for node in claster_scales:
        var nm: = node.get_meta('unit_name') as StringName
        name_to_scale[nm] = node

    # Расскрасить чётные-нечётные
    for node in get_tree().get_nodes_in_group('нечётные'):
        node.get_node('panel_rx').back_color = color_odd
        node.get_node('panel_tx').back_color = color_odd
    for node in get_tree().get_nodes_in_group('чётные'):
        node.get_node('panel_rx').back_color = color_even
        node.get_node('panel_tx').back_color = color_even

    # Подключить обработчик для приёма данных
    for nm in yems_info:
        var yems_unit = network.get_unit_instance(nm)
        yems_unit.connect('data_received', on_data_received.bind(nm))

    # Настроить таблицу
    var header_row: = []
    for cell_scn in table_headers:
        header_row.append(load(cell_scn))
    for cell_scn in table_cells:
        table_cell_row.append(load(cell_scn))
    var ctable: = $'таблица/сетка'
    ctable.set_header(header_row)
    ctable.set_header_text(table_header_text)
    ctable.set_header_property(6, 'image_file', image_file_rx)
    ctable.set_header_property(7, 'image_file', image_file_tx)
    ctable.set_headers_min_size(table_header_widths)
    ctable.set_columns_min_size(table_column_widths)
    ctable.set_rows_min_hight(table_rows_hight)
    ctable.set_header_min_hight(table_rows_hight)
    ctable.pin_header2()


## Обрабатывает событие [b]data_received[/b]
func on_data_received(data: Dictionary, nm: StringName):
    var unit_data: = yems_info[nm]
    unit_data.merge(data, true)
    if not unit_data:
        return
    var ctable: GDTable = $'таблица/сетка'
    var claster_scale: = name_to_scale[nm] as GridContainer
    var indexes: = cnames_table[nm] # Идексы строк в таблице
    map_yems_data_to_table(unit_data, ctable, indexes)
    map_yems_data_to_scale(unit_data, claster_scale)
    var inters: = find_inters(yems_info)
    map_inters_to_matrix(inters, $'матрица')
    set_timeouts(yems_info)


func set_timeouts(info: Dictionary):
    for nm in info: # nm - имя устройства
        var unit_data = info[nm]
        if not unit_data: continue
        for cls in unit_data.mcls: # cls - один кластер
            var timer_name = NodePath('%s_%s' % [nm, cls.cname])
            var timer = get_node_or_null(timer_name)
            if not timer:
                timer = Timer.new()
                timer.name = timer_name
                timer.one_shot = true
                timer.connect('timeout', _on_timeout_ttl.bind(nm, cls.cname))
                add_child(timer)
                print_debug('создан: %s' % timer_name)
            timer.start(cls.ttl)
            print_debug('пуск: %s' % timer_name)


func _on_timeout_ttl(nm, cname):
    var timer_name =  NodePath('%s_%s' % [nm, cname])
    var timer = get_node_or_null(timer_name)
    if timer:
        remove_child(timer)
        timer.queue_free()
        print_debug('удалён: %s' % timer_name)


func map_inters_to_matrix(inters: Array, matrix: GridContainer) -> void:
    var nodes = matrix.get_children()
    for item in inters:
        var tx_unit_name = item[0]
        var rx_unit_name = item[1]
        var i_col = 1 + name_to_index[tx_unit_name] # (1 +) - одна колонка для значков приёмников
        var i_row = 1 + name_to_index[rx_unit_name] # (1 +) - один ряд для значков передатчиков
        var idx = i_col + i_row * matrix.columns  # последовательный индекс в GridContainer
        var node = nodes[idx] # Искомый элемент
        node.button_pressed = true


## Отображает кластеры в таблицу
## [param nm] - имя устройства
func map_yems_data_to_table(unit_data: Dictionary, ctable: GDTable, indexes: Dictionary):
    # Обойти все кластеры устройства
    for cls in unit_data.mcls:
        # Строки для заполнения ряда
        var row_text = [cls.cname, 'Активен', '%.1f' % cls.ttl, '%.1f' % cls.daa, '%.1f' % cls.dap, '%.1f' % cls.cfb]
        # Если такой кластер уже есть, обновить его строку в таблице
        if cls.cname in indexes:
            # Получить индекс строки кластера в таблице
            var i_row = indexes[cls.cname]
            ctable.set_row_text(i_row, row_text)
        # Если такого кластера нет, создать его строку в таблице
        else:
            # Создать новый ряд
            ctable.add_row(table_cell_row)
            # Записать индекс строки в таблице для кластера
            var i_row: = indexes.size()
            indexes[cls.cname] = i_row
            # Установка высоты строки
            ctable.set_row_min_hight(i_row, table_rows_hight)


func find_inters(info: Dictionary) -> Array:
    # info - словарь, его структура
    # {
    #   "устройство": # имя устройства ("эмс-ор63")
    #   [
    #     {
    #       cname,      # имя кластера ("Кластер-0")
    #       wfb,        # ширина диапазона, МГЦ (800.0)
    #       cfb,        # центр диапазона, МГЦ (2000.0)
    #       txe,        # передатчик включен
    #       rxe         # передатчик выключен
    #     },
    #     {
    #       cname,      # имя кластера ("Кластер-1")
    #       wfb,        # ширина диапазона, МГЦ (200.0)
    #       cfb,        # центр диапазона, МГЦ (1000.0)
    #       txe,        # передатчик включен
    #       rxe         # передатчик выключен
    #     },
    #   ]
    # }
    for nm in info:
        # nm - имя устройства
        var unit_data = info[nm]
        if not unit_data: continue
        for cls in unit_data.mcls:
            # cls - один кластер
            #print_debug([cls.cname, cls.wfb, cls.cfb, cls.txe, cls.rxe])
            pass
    # заглушка для возвращаемых данных
    return [['эмс-ор63', 'эмс-ор63', 'Кластер-0', 'Кластер-0', 1600.0, 2400.0]]


## Отображает кластеры на шкале
## [param nm] - имя устройства
func map_yems_data_to_scale(unit_data: Dictionary, claster_scale: GridContainer):
    # Обойти все кластеры устройства
    for cls in unit_data.mcls:
        var c: = remap(cls.cfb, freq_min, freq_max, 0.0, 1.0)
        var w: = remap(cls.wfb, freq_min, freq_max, 0.0, 0.5)
        var l: = clampf(c - w, 0.0, 1.0)
        var h: = clampf(c + w, 0.0, 1.0)
        var scale_rx: = claster_scale.get_node('panel_rx')
        var scale_tx: = claster_scale.get_node('panel_tx')
        if cls.get('rxe', false):
            scale_rx.set_range(cls.cname, l, h, color_rx)
        else:
            scale_rx.del_range(cls.cname)
        if cls.get('txe', false):
            scale_tx.set_range(cls.cname, l, h, color_tx)
        else:
            scale_tx.del_range(cls.cname)
